// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi8fT_VeqznN7wsuTVHbsKgQCymHfuQDU',
    appId: '1:397924193709:web:4f300b732af8d79c373d24',
    messagingSenderId: '397924193709',
    projectId: 'uas-quickhelp',
    authDomain: 'uas-quickhelp.firebaseapp.com',
    storageBucket: 'uas-quickhelp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU5VrqShJ8S7rm3_4ftfF4FAT3bFXCZAM',
    appId: '1:397924193709:android:f705c01596c92100373d24',
    messagingSenderId: '397924193709',
    projectId: 'uas-quickhelp',
    storageBucket: 'uas-quickhelp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDLeYdzkbUGdrBKWQOPrOGJMPKH5nnal8',
    appId: '1:397924193709:ios:249e83d2536e7842373d24',
    messagingSenderId: '397924193709',
    projectId: 'uas-quickhelp',
    storageBucket: 'uas-quickhelp.firebasestorage.app',
    iosBundleId: 'com.example.quickhelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDLeYdzkbUGdrBKWQOPrOGJMPKH5nnal8',
    appId: '1:397924193709:ios:249e83d2536e7842373d24',
    messagingSenderId: '397924193709',
    projectId: 'uas-quickhelp',
    storageBucket: 'uas-quickhelp.firebasestorage.app',
    iosBundleId: 'com.example.quickhelp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi8fT_VeqznN7wsuTVHbsKgQCymHfuQDU',
    appId: '1:397924193709:web:f8f30afc61ba98ff373d24',
    messagingSenderId: '397924193709',
    projectId: 'uas-quickhelp',
    authDomain: 'uas-quickhelp.firebaseapp.com',
    storageBucket: 'uas-quickhelp.firebasestorage.app',
  );
}
